version: "3"
services:

  mysql:
    container_name: stalchmst-mysql
    image: mysql
    restart: always
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/init:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=template

  nginx:
    container_name: stalchmst-nginx
    image: nginx
    restart: always
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./static-content:/usr/share/nginx/html"
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80

  api:
    container_name: stalchmst-api
    build: api
    restart: always
    environment:
      - MYSQL_CONNECTION_STRING="root:toor@tcp(stalchmst-mysql:3306)/template"
      - MYSQL_HOST=stalchmst-mysql
      - MYSQL_PORT=3306
    depends_on:
      - mysql
