version: "3"
services:
  nginx:
    container_name: stalchmst-nginx
    image: nginx
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./static-content:/usr/share/nginx/html"
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
  api:
    container_name: stalchmst-api
    build: api
