version: "3"
services:

  mysql:
    container_name: stalchmst-mysql
    image: mysql
    restart: always
    volumes:
      - "./mysql/init/init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  nginx:
    container_name: stalchmst-nginx
    image: nginx
    restart: always
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./static-content:/usr/share/nginx/html"
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80

  api:
    container_name: stalchmst-api
    build: api
    restart: always
    environment:
      - MYSQL_CONNECTION_STRING=user:password@tcp(stalchmst-mysql:3306)/db
      - MYSQL_MAX_CONNECT_ATTEMPT=50
    depends_on:
      - mysql
